### ISSUE TITLE
Use of old style random number seeding in documentation

### ISSUE THREAD

**Issue by mikecroucher** [UniprJRC/FSDA#64]
I noticed in the documentation for LXS https://github.com/UniprJRC/FSDA/blob/master/toolbox/regression/LXS.m that you use the old style of seeding for random number generation

`randn('state', 123456);`

This is a bad idea since it doesn't just seed the RNG, it actually changes the algorithm for random numbers generation to a very old one.  Details at https://walkingrandomly.com/?p=2945 

I suggest you do the following instead

`rng(123456)`

**Comment by MarcoRianiUNIPR** [comment]
Dear Mike,

Thank you very much.
Inside the .m files which contain the code we have always used rng.
In the examples which illustrate the use of the m file  (that is inside
%{
....
%}
it is true that sometimes we have used the old notation with randn.

However, you are absolutely right, that this should not be done.
In the next days we will replace all instances of randn with rng


Thank you and please do not hesitate to contact us for any suggestion you might have

Best

Marco


===============================================================
Marco Riani, PhD
Professor of Statistics
Department of Economics and Management
Division of Statistics and Computing
University of Parma (http://www.unipr.it<http://www.unipr.it/>)
Via J. Kennedy 6
43100 PARMA
ITALY

Director of the Interdepartmental Centre Ro.S.A.
of the  University of Parma (http://rosa.unipr.it<http://rosa.unipr.it/>)

PHONE: +39 0521 902473
FAX:   +39 0521 902375
e-mail: ***@***.******@***.***>
http://www.riani.it<http://www.riani.it/>
https://www.researchgate.net/profile/Marco_Riani
https://scholar.google.com/citations?user=VDuzaqsAAAAJ&hl=it
https://sciprofiles.com/profile/MarcoRiani
[https://avatars0.githubusercontent.com/u/55737234?s=400&v=4]<https://github.com/UniprJRC/FSDA/wiki>
https://uniprjrc.github.io/FSDA/
--------------------------------------------------------------
Special Issue of Stats: Robust Statistics in Action II
https://www.mdpi.com/journal/stats/special_issues/EAYA8LSOPQ
Deadline for manuscript submissions: 30 June 2024

Da: Mike Croucher ***@***.***>
Inviato: lunedì 12 febbraio 2024 15:02
A: UniprJRC/FSDA ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [UniprJRC/FSDA] Use of old style random number seeding in documentation (Issue #64)


I noticed in the documentation for LXS https://github.com/UniprJRC/FSDA/blob/master/toolbox/regression/LXS.m that you use the old style of seeding for random number generation

randn('state', 123456);

This is a bad idea since it doesn't just seed the RNG, it actually changes the algorithm for random numbers generation to a very old one. Details at https://walkingrandomly.com/?p=2945

I suggest you do the following instead

rng(123456)

-

**Comment by MarcoRianiUNIPR** [comment]
Modification done, thank  you for thesuggestion
